name: "prettybot Approve"

on:
    pull_request:
        branches:
            - main

# Increase the access for the GITHUB_TOKEN
permissions:
    # This Allows the GITHUB_TOKEN to approve pull requests
    pull-requests: write
    # This Allows the GITHUB_TOKEN to auto merge pull requests
    contents: write

env:
    PR_URL: ${{github.event.pull_request.html_url}}
    # By default, GitHub Actions workflows triggered by Dependabot get a GITHUB_TOKEN with read-only permissions.
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
    prettybot:
        runs-on: ubuntu-latest
        if: ${{ (github.actor == 'Octobob') && startsWith(github.head_ref, 'prettybot/') }}
        steps:
            - name: Approve a PrettyBot created PR
              run: gh pr review --approve "$PR_URL"
